DROP TABLE IF EXISTS stats;

CREATE TABLE IF NOT EXISTS stats
(
    stat_id bigint GENERATED BY DEFAULT AS IDENTITY,
    app varchar(50) NOT NULL,
    ip varchar(50) NOT NULL,
    uri varchar(50) NOT NULL,
    timestamp timestamp WITHOUT TIME ZONE NOT NULL

    );