CREATE TABLE IF NOT EXISTS CATEGORY (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name varchar(50) UNIQUE NOT NULL
    );

CREATE TABLE IF NOT EXISTS LOCATION (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat float NOT NULL,
    lon float NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(250) NOT NULL,
    email varchar(254) UNIQUE NOT NULL
    );

CREATE TABLE IF NOT EXISTS EVENT (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar(2050),
    category bigint REFERENCES CATEGORY(id) ON DELETE CASCADE,
    confirmed_requests INT,
    created_on timestamp without time zone,
    description varchar(7050) NOT NULL,
    event_date timestamp without time zone NOT NULL,
    initiator bigint REFERENCES USERS(id) ON DELETE CASCADE,
    location bigint REFERENCES LOCATION(id) ON DELETE CASCADE,
    paid boolean NOT NULL,
    participant_limit INT NOT NULL,
    published_on timestamp without time zone,
    request_moderation boolean NOT NULL,
    state varchar(100) NOT NULL,
    title varchar(256) NOT NULL,
    views bigint NOT NULL
    );

CREATE TABLE IF NOT EXISTS COMMENTS (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text varchar(500) NOT NULL,
    event_id bigint REFERENCES EVENT(id) ON DELETE CASCADE,
    author_id bigint REFERENCES USERS(id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    edited TIMESTAMP WITHOUT TIME ZONE
    );

CREATE TABLE IF NOT EXISTS REQUESTS (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp without time zone,
    event bigint REFERENCES EVENT(id) ON DELETE CASCADE,
    requester bigint REFERENCES USERS(id) ON DELETE CASCADE,
    status varchar(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS COMPILATIONS (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title  varchar(2048) UNIQUE NOT NULL,
    pinned boolean NOT NULL
    );

CREATE TABLE IF NOT EXISTS COMPILATIONS_EVENTS (
    compilation_id bigint REFERENCES COMPILATIONS(id) ON DELETE CASCADE,
    event_id bigint REFERENCES EVENT(id) ON DELETE CASCADE
    );